version: '3.7'

services:

  mc-development:
    container_name: mc-development-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9001:9000
    environment:
      - CHOKIDAR_USEPOLLING=true 